feat: integrate launchpad indexer endpoints in UI
AFK-AlignedFamKernel/afk_monorepo pull request #146
Opened 2024-10-01 17:22 UTC by kateberryd

This PR incorporates the following endpoints into the UI:

- Deploy
- Deploy: /token
- Transaction
- Holders
- Stats

2024-10-02 13:13 UTC, kateberryd commented
**This screen displays data from tokenDeploy and tokenLaunch queries - LaunchPadComponent**
<img width="734" alt="Screenshot 2024-10-02 at 14 08 17" src="https://github.com/user-attachments/assets/a4808243-5ebb-4d82-acac-4dd5d643f063">
**View details overview screen  - LaunchDetail**
<img width="736" alt="Screenshot 2024-10-02 at 14 08 33" src="https://github.com/user-attachments/assets/01580492-e10e-43ea-95c1-d68152263340">

**Holders - TokenHolderDetails**
<img width="737" alt="Screenshot 2024-10-02 at 14 08 41" src="https://github.com/user-attachments/assets/da6f8941-00cb-4813-bb36-c4a5e16edc46">

**Token Stats - TokenStats**
<img width="739" alt="Screenshot 2024-10-02 at 14 08 47" src="https://github.com/user-attachments/assets/c6097fbc-b03a-4117-ad0f-0b89a508e1f1">

**Token Transactions - TokenTx** 
<img width="743" alt="Screenshot 2024-10-02 at 14 08 52" src="https://github.com/user-attachments/assets/9dbe9e76-7bed-4846-a96c-8c1a257cc848">

2024-10-03 12:24 UTC, MSghais requested changes

2024-10-03 12:24 UTC, MSghais commented on apps/mobile/src/components/LaunchPad/TokenHolderDetail/index.tsx
> +            <Text>{item._count.owner_address}</Text>
The count owner address need to be renderer only one time, because it's the total of holders

2024-10-04 09:09 UTC, MSghais requested changes

2024-10-04 09:09 UTC, MSghais commented on apps/mobile/src/components/LaunchPad/TokenTx/index.tsx
> +          <View style={styles.borderBottom}>
Type: buy or sell can be added. 
Also coin_received, because amount it's the amount of the ETH/STRK paid

2024-10-04 09:09 UTC, MSghais commented on apps/mobile/src/components/LaunchPad/UserShare/index.tsx
> +              Price
Amount, coin received, type of the tx are needed here.. 

Owner address is not needed, because it's every time our address no?

2024-10-04 15:16 UTC, MSghais approved these changes
Okay, we are gonna made the change requested after! 
Good work, LFG!

2024-10-04 15:26 UTC, merged