feat: added basic swap ui flow
AFK-AlignedFamKernel/afk_monorepo pull request #181
Opened 2024-10-10 20:50 UTC by addegbenga

As part of this [PR](https://github.com/AFK-AlignedFamKernel/afk_monorepo/issues/167) I added a basic swap component with initial functionality:

- Users can select two token pairs and view the estimated value in dollars.
- Added a context to trigger the swap functionality from anywhere in the app.
- Created custom hooks (`avnu hooks`) to support the swap process.

Currently, the "Swap" button opens a connected wallet, but when users are not connected the "Connect Wallet" button defaults to a Layer 1 network (e.g., MetaMask).

**Next Steps**
The "Connect Wallet" button should ideally connect to a Layer 2 network. This will enable swapping on Layer 2 as intended. Further work is required to ensure the button connects to Argent and facilitates swapping on Layer 2 networks.

2024-10-10 22:08 UTC, MSghais requested changes

2024-10-10 22:08 UTC, MSghais commented on apps/mobile/package.json
> +    "@ethersproject/units": "^5.7.0",
Can we delete a lib? We already have few utils and others lib doing it please

2024-10-10 22:08 UTC, MSghais commented on apps/mobile/src/modules/Swap/index.tsx
> +            sendTransaction(
Can you change it with a Starknet account and real calldata of the avnu?

2024-10-10 22:08 UTC, MSghais commented on apps/mobile/src/modules/Swap/index.tsx
> +  const {sendTransaction} = useSendTransaction();
AVNU is a Starknet DEX, we have hook for Starknet already and modal to connect Argent/Bravoos account

2024-10-10 22:09 UTC, MSghais commented
@addegbenga do you want to finish the Starknet account execution on this PR?

Otherwise I can merge it as it and we create another issue with the remaining tasks, let me know

2024-10-10 22:15 UTC, addegbenga commented
Yeah I will work on the rest): Thanks

2024-10-14 10:51 UTC, MSghais approved these changes
LFG

2024-10-14 10:55 UTC, merged