NIP-60 + NIP-61 Implementation
AFK-AlignedFamKernel/afk_monorepo pull request #283
Opened 2024-11-22 21:27 UTC by lindsaymoralesb

## Issue
Partially solves #168 

## Description
Hooks added for NIPs 60 (wallet event, token event, spending history event) and 61 (nut zap event).

2024-11-26 12:21 UTC, MSghais requested changes

2024-11-26 12:21 UTC, MSghais commented on apps/mobile/src/modules/CashuWallet/index.tsx
> +    const privKey = getRandomBytes(32);
Why create another key here?

2024-11-26 12:21 UTC, MSghais commented on apps/mobile/src/modules/CashuWallet/components/Send/index.tsx
> +      await Clipboard.setStringAsync(`/receive/ecash/${generatedEcash}`);
Looks the Screen is not created and not in the Router right now?

2024-11-26 13:05 UTC, lindsaymoralesb commented on apps/mobile/src/modules/CashuWallet/index.tsx
> +    const privKey = getRandomBytes(32);
From nostr docs ([NIP-60](https://github.com/nostr-protocol/nips/blob/master/60.md)):

<img width="1052" alt="Screenshot 2024-11-26 at 7 04 42 AM" src="https://github.com/user-attachments/assets/49dcc052-eab8-4e0f-8432-46674b28bc12">

2024-11-28 10:20 UTC, MSghais approved these changes
LFG good game! Yoollo merged and let's see and check more deeply after and iterate

2024-11-28 10:25 UTC, merged