Improve the search and search components of the Feed screen.
AFK-AlignedFamKernel/afk_monorepo pull request #59
Opened 2024-08-24 20:09 UTC by Dprof-in-tech

closes #36 

This is what it looks like right now
![Screenshot from 2024-08-24 21-04-45](https://github.com/user-attachments/assets/8e322b49-0d65-4c29-94c4-2f193931f32e)

2024-08-27 09:33 UTC, MSghais requested changes

2024-08-27 09:33 UTC, MSghais commented on apps/mobile/src/components/search/index.tsx
> +      {data?.pages?.map((page, index) => (
We have already a Flat list, you need to add the filter and search on the Feed not here

2024-08-27 09:33 UTC, MSghais commented on apps/mobile/src/screens/Feed/index.tsx
> +        setKinds={setKinds}
add contact list here

2024-08-27 09:33 UTC, MSghais commented on apps/mobile/src/screens/Feed/index.tsx
>          data={notes.data?.pages.flat()}
add new notes with search here

2024-08-27 20:54 UTC, Dprof-in-tech commented on apps/mobile/src/screens/Feed/index.tsx
>          data={notes.data?.pages.flat()}
done ser

2024-08-27 20:54 UTC, Dprof-in-tech commented on apps/mobile/src/screens/Feed/index.tsx
> +        setKinds={setKinds}
done ser

2024-08-27 23:05 UTC, MSghais requested changes

2024-08-27 23:05 UTC, MSghais commented on apps/mobile/src/screens/Feed/index.tsx
> -          <FlatList
Why you delete the user view in story mode?

2024-08-27 23:05 UTC, MSghais commented on apps/mobile/src/screens/Feed/index.tsx
> +          if (item.kind === undefined) {
kind === undefined?

2024-08-27 23:05 UTC, MSghais commented on apps/mobile/src/screens/Feed/index.tsx
> +          if (item.kind === undefined) {
Yes not render the BubbleUser here please..

2024-08-28 00:14 UTC, Dprof-in-tech commented
i just put back the original structure for the feed component

2024-08-28 11:40 UTC, MSghais commented
Well the PR is not finish yet. 
We are gonna merge as it is and finish at after, thank you @Dprof-in-tech

2024-08-28 14:45 UTC, MSghais approved these changes

2024-08-28 14:45 UTC, merged